import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import logo from  '../pages/Assets/logo.png'
import Header from './Components/Header/Header'
import travellergirl from '../pages/Assets/travellergirl.png'
import styles from '../styles/Home.module.css'
import playbutton from '../pages/Assets/playbutton.png'
import { Title } from './Components/Title'
const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Travel Agency</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
     <div className={styles.landing_container}>
      <Header/>
      <div className={styles.flex_container}>
        <div className={styles.leftsideTexts_Container}>
          <p className={styles.redtext}>BEST DESTINATIONS AROUND THE WORLD</p>
          <p className={styles.bigTitle}>Travel,enjoy and live a new and full life</p>
          <p className={styles.description}>Et deleniti dolor ab quibusdam blanditiis aut voluptatibus reiciendis sit repellat adipisci id enim sint. Qui velit earum et beatae maiores ut quaerat veritatis qui magni quia. Ex galisum vel nihil repellendus vel unde dignissimos et voluptate sint aut autem internos?</p>
          <div className={styles.buttoncontainer}>
          <div className={styles.moreplaybutton_container}>
          <button className={styles.morebutton}>Find out more</button>
            <div className={styles.playdemocontainer}>
              <div className={styles.playimage}>
                <Image src={playbutton}/>
              </div>
               <h5 className={styles.demotext}>Play demo</h5>
            </div>
          </div>
             </div>
          </div>
          <div className={styles.travelleriamge} >
          <Image src={travellergirl}></Image>
          </div>
        </div>
      <div className={styles.offercontainer}>
         <Title
         smalltitle='CATEGORY'
         bigtitle='We Offer Best Services'
         />
        </div>
      </div>
      
   </div>
    

    
  )
}

export default Home
