import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import logo from  '../pages/Assets/logo.png'
import Header from './Components/Header/Header'
import travellergirl from '../pages/Assets/travellergirl.png'
import styles from '../styles/Home.module.css'
import playbutton from '../pages/Assets/playbutton.png'
import { Title } from './Components/Title'
import { ServiceCard } from './Components/ServiceCard'
import weather from '../pages/Assets/weather.png'
import flight from '../pages/Assets/flight.webp'
import events from '../pages/Assets/events.png'
import settings from '../pages/Assets/settings.webp'
import bali from '../pages/Assets/bali.webp'
import taj from '../pages/Assets/taj.avif'
import uk from '../pages/Assets/us.webp'
import locationicon from '../pages/Assets/locationicon.png'
import { DestinationCard } from './Components/DestinationCard'
const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Travel Agency</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
     <div className={styles.landing_container}>
      <Header/>
      <div className={styles.content_main_container}>
      <div className={styles.flex_container}>
        <div className={styles.leftsideTexts_Container}>
          <p className={styles.redtext}>BEST DESTINATIONS AROUND THE WORLD</p>
          <p className={styles.bigTitle}>Travel,enjoy and live a new and full life</p>
          <p className={styles.description}>Et deleniti dolor ab quibusdam blanditiis aut voluptatibus reiciendis sit repellat adipisci id enim sint. Qui velit earum et beatae maiores ut quaerat veritatis qui magni quia. Ex galisum vel nihil repellendus vel unde dignissimos et voluptate sint aut autem internos?</p>
          <div className={styles.buttoncontainer}>
          <div className={styles.moreplaybutton_container}>
          <button className={styles.morebutton}>Find out more</button>
            <div className={styles.playdemocontainer}>
              <div className={styles.playimage}>
                <Image src={playbutton}/>
              </div>
               <h5 className={styles.demotext}>Play demo</h5>
            </div>
          </div>
             </div>
          </div>
          <div className={styles.travelleriamge} >
          <Image src={travellergirl}></Image>
          </div>
        </div>
      <div className={styles.offercontainer}>
        <div className={styles.titlecard_container}>
        <Title
         smalltitle='CATEGORY'
         bigtitle='We Offer Best Services'
         />
        </div>
        
         <div className={styles.services_flex_container}>
         <ServiceCard
         image={weather}
         name='Calculated weather'
         description='Et deleniti dolor ab quibusdam blanditiis aut voluptatibus reiciendis sit repellat adipisci'
         />
         <ServiceCard
         image={flight}
         name='Best Flights'
         description='Et deleniti dolor ab quibusdam blanditiis aut voluptatibus reiciendis sit repellat adipisci'
         />
          <ServiceCard
         image={events}
         name='Local Events'
         description='Et deleniti dolor ab quibusdam blanditiis aut voluptatibus reiciendis sit repellat adipisci'
         />
          <ServiceCard
         image={settings}
         name='Customization'
         description='Et deleniti dolor ab quibusdam blanditiis aut voluptatibus reiciendis sit repellat adipisci'
         />
         </div>
         <div className={styles.destination_title_card_container}>
         <Title
         smalltitle='Top Selling'
         bigtitle='Top Destinations'
         />
        <div className={styles.destinationcard_container}>
          <DestinationCard
            place={taj}
            placename='Taj mahal,india'
            likes='100.5k'
            icon={locationicon}
            days='10days Trip'
          />
          <DestinationCard
            place={bali}
            placename='bali ,indonesia'
            likes='25.5k'
            icon={locationicon}
            days='15days Trip'
          />
          <DestinationCard
            place={uk}
            placename='London,Uk'
            likes='90.5k'
            icon={locationicon}
            days='25days Trip'
          />
         </div>
        </div>
         
        </div>

        </div>
      </div>
      
   </div>
    

    
  )
}

export default Home
